CREATE TABLE IF NOT EXISTS USERS(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(50) NOT NULL,
USER_EMAIL VARCHAR(50) NOT NULL,
USER_BANK_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS BANK(
BANK_ID INT PRIMARY KEY,
BANK_BALANCE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(50) NOT NULL,
PRODUCT_PRICE INT NOT NULL,
PRODUCT_TYPE_ID INT,
PRODUCT_QUANTITY INT
);

CREATE TABLE IF NOT EXISTS TYPES(
TYPE_ID INT PRIMARY KEY,
TYPE_NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CART(
CART_ID INT AUTO_INCREMENT PRIMARY KEY,
CART_PRODUCT_ID INT NOT NULL,
CART_QUANTITY INT NOT NULL,
CART_PRODUCT_STATUS VARCHAR(50) NOT NULL,
CART_TOTAL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERED(
ORDER_ID INT PRIMARY KEY,
ORDER_USER_ID INT NOT NULL,
ORDER_STATUS VARCHAR(12) NOT NULL
);


